"""
Django settings for R4C project.

Generated by 'django-admin startproject' using Django 3.0.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    'customers.apps.CustomersConfig',
    'orders.apps.OrdersConfig',
    'robots.apps.RobotsConfig',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'R4C.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'R4C.wsgi.application'

##############
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
##############

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

##############
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators
##############

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

##############
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
##############

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Kaliningrad'

USE_I18N = True

USE_L10N = True

USE_TZ = True

##############
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
##############

STATIC_URL = '/static/'

if not DEBUG:
    STATIC_ROOT = '/home/django/www-data/example.com/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static/'),
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

##############
# Настройки авторизации allauth
##############
AUTHENTICATION_BACKENDS = [
    # Необходимо войти под именем пользователя в Django admin, независимо от `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # специфические методы аутентификации `allauth`, такие, как вход по электронной почте
    'allauth.account.auth_backends.AuthenticationBackend',
]
LOGIN_REDIRECT_URL = "/"  # Переадресация после успешного входа в систему

SITE_ID = 1  # Параметр SITE_ID указывает идентификатор базы данных Site объекта, связанного с этим конкретным файлом
# настроек.

ACCOUNT_EMAIL_VRIFICATION = 'mandatory'  # Обязательное подтверждение регистрации по электронной почте
ACCOUNT_AUTHENTIFICATION_METHOD = 'email'  # Метод входа
ACCOUNT_EMAIL_REQUIRED = True  # Установить адрес электронной почты при регистрации пользователя

##############
# Настройки почты
##############
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")  # ваше имя пользователя
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")  # Отправитель по умолчанию
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")  # Это не пароль электронной почты, а код авторизации
EMAIL_USE_TLS = True
SITE_URL = 'http://127.0.0.1:8000'  # Адрес сайта
SITE_NAME = 'Доска объявлений'  # Имя сайта

##############
# Настройки в режиме разработчика
##############

# Если включен режим разработки, то все письма отправляются в консоль
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
